# Generated by Django 3.2.3 on 2021-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=15)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(default='male', max_length=5)),
                ('WBC', models.CharField(default=' ', max_length=5)),
                ('neut', models.CharField(default=' ', max_length=2)),
                ('Lymph', models.CharField(default=' ', max_length=2)),
                ('RBC', models.FloatField(max_length=5)),
                ('HCT', models.CharField(default=' ', max_length=2)),
                ('Urea', models.CharField(default=' ', max_length=2)),
                ('HB', models.FloatField(max_length=4)),
                ('Creatinine', models.FloatField(default=1.5, max_length=4)),
                ('Iron', models.CharField(default=' ', max_length=3)),
                ('HDL', models.CharField(default=' ', max_length=3)),
                ('q1', models.CharField(max_length=3)),
                ('q2', models.CharField(max_length=3)),
                ('q3', models.CharField(max_length=3)),
                ('condition', models.CharField(default=' ', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=9)),
                ('username', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=9)),
            ],
        ),
    ]
